import { Product } from '@/entities/product'

export const KARCHER_PUZZI_8_1_ID: Product['id'] = 'karcher-puzzi-8-1'

export const KARCHER_PUZZI_8_1: Product = {
  id: KARCHER_PUZZI_8_1_ID,
  name: {
    base: 'Моющий пылесос Karcher Puzzi 8/1',
    short: 'Karcher Puzzi 8/1',
    cases: {
      accusative: 'моющий пылесос Karcher Puzzi 8/1',
      dative: 'моющему пылесосу Karcher Puzzi 8/1',
      genitive: 'моющего пылесоса Karcher Puzzi 8/1',
      instrumental: 'моющим пылесосом Karcher Puzzi 8/1',
      nominative: 'моющий пылесос Karcher Puzzi 8/1',
      prepositional: 'моющем пылесосе Karcher Puzzi 8/1',
    },
  },
  feedbackCount: 2,
  rating: 5,
  imagesURL: {
    thumbnail: `/images/products/${KARCHER_PUZZI_8_1_ID}/thumbnail.webp`,
    full: `/images/products/${KARCHER_PUZZI_8_1_ID}/full.webp`,
  },
  price: {
    useOnlyWeekdaysPrice: true,
    weekdaysHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekdays: {
      '1': 700,
      '2': 650,
      '3': 650,
      '4': 650,
      '5': 650,
      '6': 650,
      '7': 650,
      '10': 650,
      '14': 650,
      '21': 650,
      '30': 650,
      '60': 650,
    },
    weekendsHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekends: {
      '1': 700,
      '2': 650,
      '3': 650,
      '4': 650,
      '5': 650,
      '6': 650,
      '7': 650,
      '10': 650,
      '14': 650,
      '21': 650,
      '30': 650,
      '60': 650,
    },
  },
  category: 'for home',
  description:
    'Моющий пылесос Karcher Puzzi 8/1 - компактный профессиональный моющий пылесос (экстрактор) для глубокой чистки мягкой мебели, ковровых покрытий и салонов автомобилей.',
  links: {
    vk: 'https://vk.ru/market/product/moyuschiy-pylesos-karcher-puzzi-81-arenda-231455623-13594373',
    avito:
      'https://www.avito.ru/yaroslavl/predlozheniya_uslug/moyuschiy_pylesos_karcher_puzzi_81_arenda_prokat_8125993690',
  },
  equipment: [
    'Моющий пылесос',
    'Сумка для переноски и хранения',
    'Набор химии',
    'Помповый распылитель для химии',
    'Палочка для перемешивания химии',
    'Перчатки, тряпочка для очистки',
    'Щетка',
  ],
  keywords: [
    'аренда моющего пылесоса Karcher Puzzi 8/1',
    'аренда моющего пылесоса Karcher Puzzi 8/1 Ярославль',
    'прокат моющего пылесоса Karcher Puzzi 8 1',
    'прокат моющего пылесоса Karcher Puzzi 8 1 Ярославль',
    'аренда Karcher Puzzi 8/1',
    'прокат Karcher Puzzi 8/1',
    'аренда Karcher Puzzi',
    'прокат Karcher Puzzi',
    'аренда моющего пылесоса Ярославль',
    'прокат моющего пылесоса Ярославль',
    'взять в аренду моющий пылесос',
    'аренда экстрактора Ярославль',
    'прокат экстрактора для химчистки',
    'химчистка дивана своими руками',
    'химчистка ковра Ярославль',
    'чистка мягкой мебели Ярославль',
    'чистка дивана моющим пылесосом',
    'чистка ковролина Ярославль',
    'химчистка салона автомобиля Ярославль',
    'аренда оборудования для химчистки Ярославль',
    'прокат клинингового оборудования Ярославль',
    'аренда Karcher Puzzi 10/1',
    'аренда Karcher SE 4001',
    'аренда Karcher SE 4002',
    'моющий пылесос керхер аренда',
    'моющий пылесос кёрхер прокат',
    'аренда пылесоса для химчистки',
    'прокат пылесоса для чистки мебели',
  ],
}

