import { Product } from '@/entities/product'

export const CLEANBOT_TURBO_ID: Product['id'] = 'cleanbot-turbo'

export const CLEANBOT_TURBO: Product = {
  id: CLEANBOT_TURBO_ID,
  name: {
    base: 'Робот-мойщик окон CleanBot Turbo',
    short: 'Робот-мойщик окон',
    cases: {
      accusative: 'робота-мойщика окон CleanBot Turbo',
      dative: 'роботу-мойщику окон CleanBot Turbo',
      genitive: 'робота-мойщика окон CleanBot Turbo',
      instrumental: 'роботом-мойщиком окон CleanBot Turbo',
      nominative: 'робот-мойщик окон CleanBot Turbo',
      prepositional: 'роботе-мойщике окон CleanBot Turbo',
    },
  },
  feedbackCount: 0,
  rating: 0,
  imagesURL: {
    thumbnail: `/images/products/${CLEANBOT_TURBO_ID}/thumbnail.webp`,
    full: `/images/products/${CLEANBOT_TURBO_ID}/full.webp`,
  },
  price: {
    useOnlyWeekdaysPrice: true,
    weekdaysHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekdays: {
      '1': 600,
      '2': 500,
      '3': 500,
      '4': 500,
      '5': 500,
      '6': 500,
      '7': 500,
      '10': 500,
      '14': 500,
      '21': 500,
      '30': 500,
      '60': 500,
    },
    weekendsHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekends: {
      '1': 600,
      '2': 500,
      '3': 500,
      '4': 500,
      '5': 500,
      '6': 500,
      '7': 500,
      '10': 500,
      '14': 500,
      '21': 500,
      '30': 500,
      '60': 500,
    },
  },
  category: 'for home',
  description:
    'Робот-мойщик окон CleanBot Turbo - это инновационное устройство, предназначенное для эффективной и удобной мойки окон. Он оснащен мощными всасывающими присосками, которые обеспечивают надежное крепление к поверхности окна, а также высококачественными щетками и моющими средствами для тщательной очистки.',
  links: {
    vk: 'https://vk.com/market/product/robot-moyschik-okon-cleanbot-turbo-arenda-231455623-13449068',
    avito:
      'https://www.avito.ru/yaroslavl/predlozheniya_uslug/robot_moyschik_okon_cleanbot_turbo_arenda_prokat_8094614112',
  },
  equipment: [
    'Робот мойщик',
    '20 чистящих насадок из микрофибры',
    'Моющее средство во флаконе',
    'Пульверизатор с дистиллированной водой',
    'Кейс для переноски',
    'Пуль дистанционного управления',
    'Инструкция',
    'Адаптер питания, кабель питания, страховочный трос',
    'Кейс для переноски комплектующих'
  ],
  keywords: [
    'аренда робота мойщика окон',
    'аренда робота-мойщика окон',
    'прокат робота мойщика окон',
    'прокат робота-мойщика окон',
    'чистка стёкол ярославль',
    'очистка стекол ярославль',
    'аренда clean bot turbo',
    'аренда cleanbot turbo',
    'прокат cleanbot turbo',
    'прокат clean bot turbo',
    'аренда робота пылесоса для окон',
    'робот пылесос для окон',
    'оконный робот',
    'клинбот прокат',
    'стеклоочиститель аренда в ярославле',
    'мойка окон ярославль',
    'техники для уборки',
    'клининг ярославль',
    'химчистка ярославль',
    'даджет 100 ярославль',
    'даджет 200 ярославль',
    'даджет100',
    'даджет200',
    'dBot ярославль',
    'HUTT ярославль',
    'уборка окон',
  ],
}
