export const DOWNLOADED_PICO_4_ULTRA_GAMES: string[] = [
  'Arizona sunshine 2',
  'Beat saber',
  'Batman - arkham shadows',
  'Into the radius',
  'Gorn 2',
  'Job simulator',
  'I am cat',
  'Resident evil 4',
  'Peaky blinders',
  'Bonelab',
  'Just dance',
  'Hello naighbour: search and rescue',
  'Kill it with fire',
  'Marvels iron man',
  'Moss: book 2',
  'Action hero',
  'Besiege',
  'MudRunned',
  'I am monkey',
  'Blade & sorcery: nomad',
  'Warplanes: air sorp',
  'Ultimate custom night',
  'A fishermans tale 2',
  'Beauty salon simulator',
  'Moorhuhn blast',
  'Hitchhiker - a mystery game',
  'Astro hunters',
  'Call of the sea',
  'Towers and powers',
  'Sniper elite: winter warrior',
  'By grit alone',
  'Power wash simulator',
  'The fooglands',
  'Lego bricktales',
  'Barbershop simulator',
  'Escape from bunker',
  'Floor plan remastered',
  'Does it stack',
  'FrenzyVR',
  'Hyper dash',
  'Angry birds: isle of pigs',
  'Desktop clash',
]
