import { Product } from '@/entities/product'

export const DUALSENSE_EDGE_ID: Product['id'] = 'dualsense-edge'

export const DUALSENSE_EDGE: Product = {
  id: DUALSENSE_EDGE_ID,
  name: {
    base: 'Геймпад Dualsense Edge для игровой приставки PlayStation 5',
    short: 'Геймпад Dualsense Edge',
    cases: {
      accusative: 'геймпад Dualsense Edge для PlayStation 5',
      dative: 'геймпаду Dualsense Edge для PlayStation 5',
      genitive: 'геймпада Dualsense Edge для PlayStation 5',
      instrumental: 'геймпад Dualsense Edge для PlayStation 5',
      nominative: 'геймпадом Dualsense Edge для PlayStation 5',
      prepositional: 'геймпада Dualsense Edge для PlayStation 5',
    },
  },
  feedbackCount: 0,
  rating: 0,
  imagesURL: {
    thumbnail: `/images/products/${DUALSENSE_EDGE_ID}/thumbnail.webp`,
    full: `/images/products/${DUALSENSE_EDGE_ID}/full.webp`,
  },
  price: {
    useOnlyWeekdaysPrice: true,
    weekdaysHideDays: ['1', '2', '3', '4', '5', '6', '10'],
    weekdays: {
      '1': 0,
      '2': 0,
      '3': 0,
      '4': 0,
      '5': 0,
      '6': 0,
      '7': 180,
      '10': 180,
      '14': 170,
      '21': 160,
      '30': 140,
      '60': 120,
    },
    weekendsHideDays: ['1', '2', '3', '4', '5', '6', '10'],
    weekends: {
      '1': 0,
      '2': 0,
      '3': 0,
      '4': 0,
      '5': 0,
      '6': 0,
      '7': 180,
      '10': 180,
      '14': 170,
      '21': 160,
      '30': 140,
      '60': 120,
    },
  },
  category: 'rest and leisure',
  description:
    'Dualsense Edge - Улучшенная версия геймпада Dualsense для игровой приставки PlayStation 5. Геймпад оснащён настраиваемыми кнопками, регулируемыми курками и триггерами, а также сменными стиками для максимальной персонализации игрового процесса. Подходит для компьютера.',
  links: {
    vk: 'https://vk.com/market/product/geympad-dualsense-ps5-arenda-231455623-13472316',
  },
  equipment: [
    'Геймпад Dualsense Edge для игровой консоли PlayStation 5 или Компьютера',
    'Кабель для зарядки',
    'Кейс для переноски',
    'Сменные насадки и лепестки'
  ],
  keywords: [
    'аренда геймпада dualsense edge',
    'прокат геймпада dualsense edge',
    'аренда контроллера dualsense edge',
    'прокат контроллера dualsense edge',
    'аренда геймпада dualsense edge для игровой консоли PlayStation 5',
    'прокат геймпада dualsense edge для игровой консоли PlayStation 5',
    'аренда геймпада dualsense edge для PlayStation 5',
    'прокат геймпада dualsense edge для PlayStation 5',
    'dualsense edge для ps 5',
    'dualsense edge для ps 5',
    'dualsense edge для ps5',
    'dualsense edge для ps5',
    'dualsense edge для пс 5',
    'dualsense edge для пс 5',
    'dualsense edge для пс5',
    'dualsense edge для пс5',
    'геймпад dualsense edge для пс',
    'геймпад dualsense edge для пс',
    'арендовать геймпад dualsense edge для консоли PlayStation 5',
    'арендовать контроллер dualsense edge для PlayStation 5',
    'аренда геймпада dualsense edge для PlayStation 5 Ярославль',
    'купить dualsense edge Ярославль',
    'купить',
  ],
}
