import { Product } from '@/entities/product'

export const KARCHER_SC4_DELUXE_ID: Product['id'] = 'karcher-sc4-deluxe'

export const KARCHER_SC4_DELUXE: Product = {
  id: KARCHER_SC4_DELUXE_ID,
  name: {
    base: 'Пароочиститель Karcher SC4 Deluxe',
    short: 'Пароочиститель Karcher SC4 Deluxe',
    cases: {
      accusative: 'пароочиститель Karcher SC4 Deluxe',
      dative: 'пароочистителю Karcher SC4 Deluxe',
      genitive: 'пароочистителя Karcher SC4 Deluxe',
      instrumental: 'пароочистителем Karcher SC4 Deluxe',
      nominative: 'пароочиститель Karcher SC4 Deluxe',
      prepositional: 'пароочистителе Karcher SC4 Deluxe',
    },
  },
  feedbackCount: 0,
  rating: 0,
  imagesURL: {
    thumbnail: `/images/products/${KARCHER_SC4_DELUXE_ID}/thumbnail.webp`,
    full: `/images/products/${KARCHER_SC4_DELUXE_ID}/full.webp`,
  },
  price: {
    useOnlyWeekdaysPrice: true,
    weekdaysHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekdays: {
      '1': 800,
      '2': 700,
      '3': 700,
      '4': 700,
      '5': 700,
      '6': 700,
      '7': 700,
      '10': 700,
      '14': 700,
      '21': 700,
      '30': 700,
      '60': 700,
    },
    weekendsHideDays: ['3', '4', '5', '6', '7', '10', '14', '21', '30', '60'],
    weekends: {
      '1': 800,
      '2': 700,
      '3': 700,
      '4': 700,
      '5': 700,
      '6': 700,
      '7': 700,
      '10': 700,
      '14': 700,
      '21': 700,
      '30': 700,
      '60': 700,
    },
  },
  category: 'for home',
  description:
    'Пароочиститель Karcher SC4 Deluxe - это мощный и эффективный инструмент для уборки, который использует пар для удаления грязи, жира и бактерий с различных поверхностей. Этот пароочиститель идеально подходит для очистки кухонных плит, духовок, кафельных стен, окон и других поверхностей в доме.',
  links: {
    vk: 'https://vk.com/market/product/paroochistitel-karcher-sc4-delux-arenda-231455623-13461499',
    avito:
      'https://www.avito.ru/yaroslavl/predlozheniya_uslug/paroochistitel_karcher_sc4_delux_arenda_prokat_8094551722',
  },
  equipment: [
    'Пароочиститель',
    'Сумка для переноски и хранения',
    'Насадка для пола + 2 салфетки',
    'Насадка для поверхностей + 2 салфетки',
    '6 насадок различной формы и точечное сопло',
    '2 Удлинителя рукоятки',
  ],
  keywords: [
    'аренда пароочистителя Karcher SC4 Deluxe',
    'аренда пароочистителя Karcher SC4 Deluxe Ярославль',
    'прокат пароочистителя Karcher SC4 Deluxe',
    'прокат пароочистителя Karcher SC4 Deluxe Ярославль',
    'химчистка пароочистителем',
    'химчистка ярославль',
    'уборка ярославль',
    'клининг ярославль',
    'аренда клинингового оборудования ярославль',
    'арендовать Karcher sc 4',
    'аренда Karcher sc 4',
    'аренда Karcher sc3',
    'аренда Karcher sc 3',
    'аренда Karcher sc2',
    'аренда Karcher sc 2',
    'аренда Karcher sc5',
    'аренда Karcher sc 5',
    'прокат оборудования для чистки',
    'аренда оборудования для чистки',
    'прокат пароочистителя кёрхер',
    'аренда пароочистителя керхер',
    'взять в аренду парогенератор',
    'дезинфекция паром',
    'химическая очистка',
    'отпариватель ярославль',
    'аренда отпаривателя в Ярославле',
  ],
}
