export const DOWNLOADED_PICO_4_GAMES: string[] = [
  'Metro Awakening',
  'Beat Saber',
  'Superhot',
  'VR chat',
  'GORN 2',
  'BONELAB',
  'I am cat',
  'Job simulator',
  'Fruit Ninja',
  'Hello Neighbour: Search and rescue',
  'Escape from bunker',
  'Drop dead: the cabin',
  'Barbershop simulator VR',
  'Does it stack?',
  'Floor plan Remastered',
  'Frenzy VR',
  'Hyper dash',
  'Gravity sketch',
  'Kill it with fire VR',
  'Just dance VR',
  'LEGO Bricktales',
  'Smalland VR',
  'The Foglands',
  'Sclerosis',
  'Power Wash simulator',
  'Sniper Elite VR: Winter Warrior',
  'By grit alone',
  'Corridor',
  'Call of the Sea VR',
  'Powder',
  'Towers and powers',
  'Astro Hunters',
  'Hitchhiker - A mystery game',
  'Beauty salon simulator VR',
  'Black hole pool',
  'Demeo',
  'Warplanes: air corp',
  'A fisherman`s tale 2',
  'Eye of the temple',
  'Moorhuhn VR blast',
]
